# https://kubernetes.io/docs/concepts/overview/working-with-objects/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: houseapp-light-deployment
spec:
  selector:
    matchLabels:
      app: light-api
  replicas: 1
  template:
    metadata:
      labels:
        app: light-api
    spec:
      containers:
        - name: light-api
          image: madworld/houseapp/light:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: houseapp-light-loadbalancer
spec:
  selector:
    app: light-api
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 80
  type: LoadBalancer
