# https://kubernetes.io/docs/concepts/overview/working-with-objects/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: houseapp-weather-deployment
spec:
  selector:
    matchLabels:
      app: weather-api
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: madworld/houseapp/weather:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: houseapp-weather-loadbalancer
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: houseapp-weather-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: www.houseapp.local
      http:
        paths:
          - path: /weather/
            pathType: Prefix
            backend:
              service:
                name: houseapp-weather-loadbalancer
                port:
                  number: 8081
          - path: /weather/
            pathType: Prefix
            backend:
              service:
                name: houseapp-weather-loadbalancer
                port:
                  number: 443
