apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: houseapp-ingress
  namespace: houseapp
spec:
  rules:
    - host: api.myhouseapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: houseapp-api-loadbalancer
                port:
                  number: 80
    - host: jobrunner.myhouseapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: houseapp-jobrunner-loadbalancer
                port:
                  number: 80
    - host: ui.myhouseapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: houseapp-ui-loadbalancer
                port:
                  number: 80