# https://kubernetes.io/docs/concepts/overview/working-with-objects/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: houseapp-api-deployment
  namespace: houseapp
spec:
  selector:
    matchLabels:
      app: houseapp-api
  replicas: 1
  template:
    metadata:
      labels:
        app: houseapp-api
    spec:
      containers:
        - name: houseapp-api
          image: madworld/houseapp/api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: houseapp-api-loadbalancer
  namespace: houseapp
spec:
  selector:
    app: houseapp-api
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 80
  type: LoadBalancer
