# https://kubernetes.io/docs/concepts/overview/working-with-objects/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: houseapp-weather-deployment
  namespace: houseapp
spec:
  selector:
    matchLabels:
      app: weather-api
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: madworld/houseapp/weather:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: houseapp-weather-loadbalancer
  namespace: houseapp
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      name: http
      port: 8083
      targetPort: 80
  type: LoadBalancer
